"use client";

import { useRouter } from "next/navigation";
import { useStore } from "@/lib/store";
import { Badge, Button, Wordmark } from "@/components/ui";

const STEPS = [
  { n: "01", title: "Find creators your buyers trust", body: "Ranked by audience fit, not follower count. Every score is explainable." },
  { n: "02", title: "Build a campaign brief in minutes", body: "Objectives, key messages, guidelines and tracking links, generated from your landing page." },
  { n: "03", title: "Manage every collaboration", body: "Invite, review drafts, request changes, approve, schedule. One pipeline." },
  { n: "04", title: "Track reach, clicks and leads", body: "Attributed pipeline per post, with cost per lead against your LinkedIn Ads baseline." },
  { n: "05", title: "Pay creators without the admin", body: "Contract, invoice and payout tracked as states. No chasing." },
];

export default function Landing() {
  const { setRole } = useStore();
  const router = useRouter();

  const enter = (role: "brand" | "creator") => {
    setRole(role);
    router.push(role === "brand" ? "/brand" : "/creator");
  };

  return (
    <div className="min-h-dvh bg-surface">
      {/* ------------------------------------------------------------- nav */}
      <header className="mx-auto flex h-16 max-w-[1180px] items-center justify-between px-5">
        <Wordmark />
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" onClick={() => enter("creator")}>
            I&apos;m a creator
          </Button>
          <Button size="sm" onClick={() => enter("brand")}>
            Launch a campaign
          </Button>
        </div>
      </header>

      {/* ----------------------------------------------------------- hero */}
      <section className="relative overflow-hidden">
        <div
          className="pointer-events-none absolute inset-x-0 top-0 h-[420px]"
          style={{
            background:
              "linear-gradient(180deg,#dbe6ff 0%,#eef3ff 42%,rgba(255,255,255,0) 100%)",
          }}
          aria-hidden="true"
        />
        <div className="relative mx-auto max-w-[1180px] px-5 pt-14 pb-16 text-center sm:pt-20">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full bg-surface/80 px-3 py-1.5 ring-1 ring-line">
            <span className="relative flex h-1.5 w-1.5">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-brand opacity-60" />
              <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-brand" />
            </span>
            <span className="text-[12px] font-medium text-ink-soft">
              Where B2B brands work with creators
            </span>
          </div>

          <h1 className="mx-auto max-w-[720px] text-[40px] font-semibold leading-[1.05] tracking-[-0.03em] sm:text-[58px]">
            The B2B LinkedIn
            <br />
            Creator Marketplace.
          </h1>

          <p className="mx-auto mt-5 max-w-[560px] text-[15px] leading-relaxed text-ink-soft sm:text-base">
            Find the creators your buyers already trust, launch campaigns in days, and
            track the clicks, leads and pipeline generated by every post.
          </p>

          {/* Two doors, because the product has two sides. No signup wall. */}
          <div className="mx-auto mt-9 grid max-w-[620px] gap-3 sm:grid-cols-2">
            <button
              onClick={() => enter("brand")}
              className="group rounded-card bg-ink p-5 text-left text-white transition-transform hover:-translate-y-0.5"
            >
              <p className="text-[11px] font-semibold tracking-[0.09em] text-white/55 uppercase">
                For brands
              </p>
              <p className="mt-2 text-[17px] font-semibold">Launch a campaign →</p>
              <p className="mt-1.5 text-[13px] leading-snug text-white/65">
                Book creators, brief them, trace pipeline back to each post.
              </p>
            </button>
            <button
              onClick={() => enter("creator")}
              className="group rounded-card bg-brand p-5 text-left text-white transition-transform hover:-translate-y-0.5"
            >
              <p className="text-[11px] font-semibold tracking-[0.09em] text-white/60 uppercase">
                For creators
              </p>
              <p className="mt-2 text-[17px] font-semibold">Get paid to post →</p>
              <p className="mt-1.5 text-[13px] leading-snug text-white/70">
                Choose deals from brands you use. Paid within 24h, no negotiating.
              </p>
            </button>
          </div>

          <p className="mt-5 text-[12.5px] text-muted">
            No account needed — both sides are open, and you can switch between them at
            any time.
          </p>
        </div>
      </section>

      {/* ---------------------------------------------------------- proof */}
      <section className="border-y border-line bg-canvas">
        <div className="mx-auto grid max-w-[1180px] grid-cols-2 gap-px px-5 py-8 sm:grid-cols-4">
          {[
            ["€18", "avg cost per qualified click", "vs €55–90 on LinkedIn Ads"],
            ["12%", "avg CTR on creator posts", "vs 0.8% sponsored content"],
            ["2,000+", "vetted B2B creators", "across 100 countries"],
            ["3–5×", "reach vs a company page", "LinkedIn favours people"],
          ].map(([big, label, sub]) => (
            <div key={label} className="px-2 text-center sm:px-4">
              <p className="tnum text-[26px] font-semibold tracking-tight">{big}</p>
              <p className="mt-1 text-[12.5px] font-medium text-ink-soft">{label}</p>
              <p className="mt-0.5 text-[11.5px] text-muted">{sub}</p>
            </div>
          ))}
        </div>
        <p className="pb-7 text-center text-[11px] text-muted">
          Naano marketplace data, Q1 2026 · 312 campaigns
        </p>
      </section>

      {/* ---------------------------------------------------------- steps */}
      <section className="mx-auto max-w-[1180px] px-5 py-16">
        <p className="eyebrow mb-3 text-center">One platform, from brief to results</p>
        <h2 className="mx-auto max-w-[540px] text-center text-[30px] font-semibold leading-tight tracking-[-0.02em]">
          Run creator campaigns from one place.
        </h2>
        <div className="mt-12 grid gap-x-10 gap-y-8 sm:grid-cols-2 lg:grid-cols-3">
          {STEPS.map((s) => (
            <div key={s.n} className="border-t border-line pt-4">
              <p className="tnum text-[12px] font-semibold text-brand">{s.n}</p>
              <p className="mt-2 text-[15px] font-semibold tracking-tight">{s.title}</p>
              <p className="mt-1.5 text-[13.5px] leading-relaxed text-muted">{s.body}</p>
            </div>
          ))}
          <div className="rounded-card bg-canvas p-5 ring-1 ring-line">
            <Badge tone="brand">Rebuild note</Badge>
            <p className="mt-2.5 text-[13.5px] leading-relaxed text-ink-soft">
              This is an independent rebuild of Naano, built in a day. Real auth and
              payment rails are deliberately left out — everything else works, on both
              sides, against seeded data.
            </p>
          </div>
        </div>
      </section>

      <footer className="border-t border-line">
        <div className="mx-auto flex max-w-[1180px] flex-col items-center gap-2 px-5 py-8 text-center">
          <Wordmark className="text-ink" />
          <p className="text-[12px] text-muted">
            Rebuild of naano.com · not affiliated with Naano
          </p>
        </div>
      </footer>
    </div>
  );
}
